swagger: "2.0"
info:
  description: "Documentación de la definición de los servicios NoLogin,Multiva,Legosoft" 
  version: "0.1.0"
  title: "Grupo Financiero Multiva"
host: "200.39.24.141"
basePath: "/"
tags:
- name: "Core Bancario"
  description: "Primer Login (Dinámico  y Estático)"
  externalDocs:
    description: "Primer Login"
    url: "http://200.39.24.141:9092/docs"
paths: 
  /Cliente:
    post:
      tags:
      - "Cliente"
      summary: "/Cliente"
      description: "Realiza la consulta de el cliente"
      operationId: "clientePOST"
      parameters:
      - in: "body"
        name: "Cliente"
        description: "Respuesta de datos del cliente"
        required: true
        schema:
          $ref: "#/definitions/entradaCliente-in"
      responses:
        200:
          description: "cliente"
          schema:
            $ref: "#/definitions/cliente-res"
        403:
          description: "Cliente no encontrado"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Cliente no encontrado"
          schema:
            $ref: "#/definitions/Error"            
      x-swagger-router-controller: "Cliente"
  /Contrato:
    post:
      tags:
      - "Contrato"
      summary: "/Contrato"
      description: "Realiza la modificacion del contrato"
      operationId: "contratoPOST"
      parameters:
      - in: "body"
        name: "Contrato"
        description: "Respuesta"
        required: true
        schema:
          $ref: "#/definitions/contrato-mod-in"
      responses:
        200:
          description: "Contrato Modificacion exitosa"
          schema:
            $ref: "#/definitions/contrato-mod-res"
        403:
          description: "Cliente no encontrado"
          schema:
            $ref: "#/definitions/ErrorContratoModificacion"
        404:
          description: "Cliente no encontrado"
          schema:
            $ref: "#/definitions/ErrorContratoModificacion"            
      x-swagger-router-controller: "Contrato"
      
definitions:
  contrato-mod-in:
    properties:
      usuario:
        type: "string"
        example: "11212112"
      contratoAceptado:
        type: "string"
        example: "7656715672"
  contrato-mod-res:
    properties:
      respuesta:
        type: "string"
        example: "OK"
      CodigoRespuesta:
        type: "string"
        example: "Operación correcta: 0"
  entradaCliente-in:
    properties:
      Numerocliente:
        type: "integer"
        example: 1
  cliente-res:
    properties:
      CodigoRespuesta:
        type: "integer"
        example: 1
      DescripcionResp:
        type: "string"
        example: "Datos del clinete"
      NumCliente:
        type: "string"
        example: "1234"
      Nombre:
        type: "string"
        example: "Agustin"
      Direccion:
        type: "string"
        example: "5 de mayo"
      Poblacion:
        type: "string"
        example: "polanco"
      Ciudad:
        type: "string"
        example: "mexico"
      Estado:
        type: "string"
        example: "mexico"
      CP:
        type: "string"
        example: "50010"
      RFC:
        type: "string"
        example: "RYTUYT7867687"
      Telefono1:
        type: "string"
        example: "55556262672"
      Telefono2:
        type: "string"
        example: "5556262626"
      Celular:
        type: "string"
        example: "555762272"
      Mail:
        type: "string"
        example: "agusting@hormail.com"
      TipoPersona:
        type: "string"
        example: "Fisica"
      Estatus:
        type: "string"
        example: ""
      Sucursal:
        type: "string"
        example: "1"
      ESVIP:
        type: "string"
        example: "1"
  Error:
    properties:
      CodigoRespuesta:
        type: "string"
        example: "Cliente no encontrado"
        description: "Cliente no encontrado"
  ErrorContratoModificacion:
    properties:
      CodigoRespuesta:
        type: "string"
        example: "No se encuentra el usuario: 32"
        description: "No se encuentra el usuario: 32"
  
