---
swagger: "2.0"
info:
  description: "Documentación de los servicios Multiva Sprint 1  <a href='http://drive.google.com/open?id=0B5MVImiMKmoPbk1RS09LWjR1aTQ'>Documento Compartido</a>" 
  version: "0.1.0"
  title: "Grupo FInzanciero Multiva"
host: "200.39.24.141:9090"
basePath: "/"
tags:
- name: "Core Bancario"
  description: "Primer Login (Dinámico  y Estático)"
  externalDocs:
    description: "Primer Login"
    url: "http://200.39.24.141:9090/docs"
paths:
  /Cliente:
    post:
      tags:
      - "Cliente"
      summary: "/Cliente"
      description: "Realiza la consulta de el cliente"
      operationId: "clientePOST"
      parameters:
      - in: "body"
        name: "Cliente"
        description: "Respuesta de datos del cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        403:
          description: "Cliente no encontrado"
          schema:
            $ref: "#/definitions/inline_response_403"
        404:
          description: "Cliente no encontrado"
          schema:
            $ref: "#/definitions/inline_response_403"
      x-swagger-router-controller: "Cliente"
 
  /Validaotp:
    post:
      tags:
      - "OTP"
      description: "Servicio que realiza la validación del OTP"
      operationId: "validaOTP"
      parameters:
      - in: "body"
        name: "validaOTP"
        description: "Se requiere la validación de VACMAN del usuario y su OTP"
        required: true
        schema:
          $ref: "#/definitions/validaOTP"
      responses:
        200:
          description: "Usuario correcto y token correcto: 0"
          schema:
            $ref: "#/definitions/inline_response_403_1"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        400:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "OTP"
    x-swagger-router-controller: "validaOTP"
  /cambioPwd:
    post:
      tags:
      - "Contraseña"
      description: "Se requiere la validacion de la contraseña actual despues que\
        \ se compare la nueva contraseña si los dos pasos son exitoso se requiere\
        \ realizar una modificacion al atributo userPassword en LDAP para el numero\
        \ del cleinte (uid=$numCliente,ou=people,dc=multiva,dc=mx) previamente obtenido\
        \ en la entradas y se coloca el nuevo password proporcionado."
      operationId: "cambioPwd"
      parameters:
      - in: "body"
        name: "cambioPwd"
        description: "Se requiere la validacion de la contraseña actual  "
        required: true
        schema:
          $ref: "#/definitions/cambioPwd"
      responses:
        200:
          description: "Cambio de contraseña exitoso: 0"
          schema:
            $ref: "#/definitions/inline_response_200_3"
        500:
          description: "No coinciden las nuevas contraseñas: 48"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        400:
          description: "Contraseña actual errónea: 49"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        
      x-swagger-router-controller: "Contrasea"
    x-swagger-router-controller: "cambioPwd"
  /contrato:
    post:
      tags:
      - "Contrato"
      description: "Se requiere obtener el dato del atributo contratoAceptado: en\
        \ LDAP por medio de un ldapsearch -h ip-server -p 389 –D uid=$idCliente,ou=people,dc=multiva,dc=mx\
        \ -w $password -b  -s base contratoAceptado."
      operationId: "contrato"
      parameters:
      - in: "body"
        name: "contrato"
        description: "Se requiere la validacion de la contraseña actual  "
        required: true
        schema:
          $ref: "#/definitions/contrato"
      responses:
        200:
          description: "Operación correcta: 0"
          schema:
            $ref: "#/definitions/inline_response_200_4"
        500:
          description: "valor del atributo nulo: 41"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        400:
          description: "No se encuentra el usuario: 32"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Contrato"
    x-swagger-router-controller: "contrato"
definitions:
  
  Cliente:
    properties:
      Numerocliente:
        type: "integer"
        example: 1
  inline_response_200:
    properties:
      CodigoRespuesta:
        type: "integer"
        example: 1
      DescripcionResp:
        type: "string"
        example: "Datos del clinete"
      NumCliente:
        type: "string"
        example: "1234"
      Nombre:
        type: "string"
        example: "Agustin"
      Direccion:
        type: "string"
        example: "5 de mayo"
      Poblacion:
        type: "string"
        example: "polanco"
      Ciudad:
        type: "string"
        example: "mexico"
      Estado:
        type: "string"
        example: "mexico"
      CP:
        type: "string"
        example: "50010"
      RFC:
        type: "string"
        example: "RYTUYT7867687"
      Telefono1:
        type: "string"
        example: "55556262672"
      Telefono2:
        type: "string"
        example: "5556262626"
      Celular:
        type: "string"
        example: "555762272"
      Mail:
        type: "string"
        example: "agusting@hormail.com"
      TipoPersona:
        type: "string"
        example: "Fisica"
      Estatus:
        type: "string"
        example: ""
      Sucursal:
        type: "string"
        example: "1"
      ESVIP:
        type: "string"
        example: "1"
  inline_response_403:
    properties:
      Error:
        type: "string"
        example: "Error"
        description: "Respuesta"
  inline_response_403_1:
     properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"
      DescRespuesta:
        type: "string"
        example: "string"
      Antiphishing:
        type: "integer"
        example: "integer"
  validaOTP:
    properties:
      Usuario:
        type: "string"
        example: "123456789"
      OTP:
        type: "string"
        example: "12345tftg56577654"
      Tipo:
        type: "integer"
        example: 1
  inline_response_200_2:
    properties:
      codigoError:
        type: "integer"
        example: "integer"
      mensajeError:
        type: "string"
        example: "string"

  cambioPwd:
    properties:
      usuario:
        type: "string"
        example: "123456789"
      password:
        type: "string"
        example: "12345tftg5657765412wqsdwdwe23e3r43rd"
      nuevo password:
        type: "string"
        example: "12345tftg5657765412wqsdwdwe23e3r43rd"
      confirma nuevo password:
        type: "string"
        example: "12345tftg5657765412wqsdwdwe23e3r43rd"
  inline_response_200_3:
    properties:
      CodigoRespuesta:
        type: "string"
        example: "0"
      DescRespuesta:
        type: "string"
        example: "Cambio de contraseña exitoso"
      Antiphishing:
        type: "string"
        example: "test1"
 
  contrato:
    properties:
      usuario:
        type: "string"
        example: "wined"
  inline_response_200_4:
    properties:
      Valor obtenido del atributo contrato Aceptado.:
        type: "string"
        example: "0"
      Código de retorno:
        type: "string"
        example: "Operación correcta"
 
