---
swagger: "2.0"
info:
  description: "Documentación de los servicios Multiva Sprint 1  <a href='https://drive.google.com/open?id=0B_OaZlYG0i2ndHJUT3VFem5LWlk'>Documento Compartido</a>" 
  version: "0.1.0"
  title: "Grupo Financiero Multiva"
host: "200.39.24.141"
basePath: "/BEO"
tags:
- name: "Core Bancario"
  description: "Grupo Financiero Multiva"
  externalDocs:
    description: "Primer Login"
    url: "http://200.39.24.141:9090/docs"
paths:
  /consultaDatosBasicos:
    post:
      tags:
      - "ESB Fuse"
      description: "Consolidar la información relevante respecto al diseño de la operacion /consultaDatosBasicos del servicio /cliente requerida para la integración de Multivanet con T24"
      parameters:
      - in: "body"
        name: "consultaDatosBasicos,"
        description: "Consumidor  que dibuja encabezado con datos de cliente"
        required: true
        schema:
          $ref: "#/definitions/consultaDatosBasicos-in"
      responses:
        200:
          description: "En esta interfaz se describe un servicio dummy que se publicara para el uso del consumidor en tanto se completa la integracion del ESB a T24. Bajo el entendido de que la firma expuesta en este servicio dummy no cambiara cuando el desarrollo termine"
          schema:
            $ref: "#/definitions/consultaDatosBasicos-res"
            
  /consultaServiciosContratados:
    post:
      tags:
      - "ESB Fuse"
      description: "Consolidar la información relevante respecto al diseño de la operacion /consultaServiciosContratados del servicio /cliente requerida para la integración de Multivanet con T24"
      parameters:
      - in: "body"
        name: "consultaServiciosContratados"
        description: "Devuelve un listado de los servicios existentes para personas morales, indicando cuales de ellos han sido contratados por la persona proporcionada"
        required: true
        schema:
          $ref: "#/definitions/consultaServiciosContratados-in"
      responses:
        200:
          description: "Devuelve un listado de los servicios existentes para personas morales, indicando cuales de ellos han sido contratados por la persona proporcionada."
          schema:
            $ref: "#/definitions/consultaServiciosContratados-res"
            
  /consultaProductosContratados:
    post:
      tags:
      - "ESB Fuse"
      description: "Consolidar la información relevante respecto al diseño de la operacion /consultaProductosContratados del servicio /cliente requerida para la integración de Multivanet con T24"
      parameters:
      - in: "body"
        name: "consultaProductosContratados"
        description: "Devuelve un listado de los productos bancarios que han sido contratados por la persona proporcionada"
        required: true
        schema:
          $ref: "#/definitions/consultaProductosContratados-in"
      responses:
        200:
          description: "Devuelve un listado de los productos bancarios que han sido contratados por la persona proporcionada"
          schema:
            $ref: "#/definitions/consultaProductosContratados-res"
  /Validaotp:
    post:
      tags:
      - "ESB Fuse"
      description: "Servicio que realiza la validación del OTP"
      parameters:
      - in: "body"
        name: "validaOTP"
        description: "Se requiere la validación de VACMAN del usuario y su OTP"
        required: true
        schema:
          $ref: "#/definitions/validaOTP"
      responses:
        200:
          description: "Tipos de datos de la respuesta del servicio"
          schema:
            $ref: "#/definitions/Validaotp-res"
        
  /cambioContrasena:
    post:
      tags:
      - "ESB Fuse"
      description: "Se requiere la validacion de la contraseña actual despues que
        se compare la nueva contraseña si los dos pasos son exitoso se requiere
        realizar una modificacion al atributo userPassword en LDAP para el numero
        del cleinte previamente obtenido en la entradas y se coloca el nuevo password proporcionado"
      parameters:
      - in: "body"
        name: "cambioPwd"
        description: "Se requiere la validacion de la contraseña actual  "
        required: true
        schema:
          $ref: "#/definitions/cambiapassword-in"
      responses:
        200:
          description: "Estructura de la respuesta del servicio"
          schema:
            $ref: "#/definitions/cambiapassword-res"
        
       
  
  
 
definitions:
  cambiapassword-in:
    properties:
      Usuario:
        type: "string"
        example: "123456789"
      Contraseña_original:
        type: "string"
        example: "12345pwd"
      Nueva_contraseña:
        type: "string"
        example: "pwd1234"
      Comprueba_contraseña:
        type: "string"
        example: "pwd1233"
        
  cambiapassword-res:
    properties:
      CodigoRespuesta:
        type: "integer"
        format: "int64"
        example: "Long"
        
  consultaProductosContratados-in:
    required:
      - idPersona
      - canal
    properties:
      idPersona:
        type: number
        example: "1025478963"
      ticket:
          $ref: "#/definitions/consultaProductosContratadosticket"
      canal:
        type: "string"
        minLength: 1
        maxLength: 5
        example: "CUBA1234575SDF"
        
  consultaProductosContratados-res:
    required:
      - responseStatus
    properties:
      listaServicios:
         type: "array"
         items:
          $ref: "#/definitions/ServiciosContratadosListaServicios"
      responseStatus:
        type: integer
        example: "String"
      responseError:
        type: "string"
        example: "String"
        
  consultaProductosContratadosticket:
    properties:
      id_user:
        type: "string"
        example: ""
      id_creds:
        type: "string"
        example: ""
        
  Validaotp-res:
     properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"
      DescRespuesta:
        type: "string"
        example: "string"
      Antiphishing:
        type: "integer"
        example: "integer"
        
  validaOTP:
    properties:
      Usuario:
        type: "string"
        example: "123456789"
      OTP:
        type: "string"
        example: "12345tftg56577654"
      Tipo:
        type: "integer"
        example: 1
  



  consultaServiciosContratados-in:
    required:
      - idPersona
      - canal
    properties:
      idPersona:
        type: number
        example: "1025478963"
      ticket:
          $ref: "#/definitions/consultaServiciosContratadosticket"
      canal:
        type: "string"
        minLength: 1
        maxLength: 5
        example: "CUBA1234575SDF"
        
  consultaServiciosContratadosticket:
    required:
      - id_user
      - id_creds
    properties:
      id_user:
        type: "string"
        example: ""
      id_creds:
        type: "string"
        example: ""
  
  
  
  
  ticket:
    required:
      - id_user
      - id_creds
    properties:
      id_user:
        type: "string"
        example: ""
      id_creds:
        type: "string"
        example: ""
  
  
  consultaServiciosContratados-res:
    required:
      - responseStatus
    properties:
      listaServicios:
         type: "array"
         items:
          $ref: "#/definitions/ServiciosContratadosListaServicios"
      responseStatus:
        type: integer
        example: "String"
      responseError:
        type: "string"
        example: "String"
      
     


  
  consultaDatosBasicos-in:
    required:
      - idPersona
      - canal
    properties:
      idPersona:
        type: number
        example: "1025478963"
      ticket:
          $ref: "#/definitions/ticket"
      canal:
        type: "string"
        minLength: 1
        maxLength: 5
        example: "CUBA1234575SDF"
        
        
  ServiciosContratadosListaServicios:
    properties:
      nombre:
        type: "string"
        example: "String"
      contratado:
        type: boolean
        example: "Boolean"
  
  consultaDatosBasicos-res:
    required:
      - numCliente
      - nombre
    properties:
      numCliente:
        type: "integer"
        format: "int64"
        example: "Long"
      nombre:
        type: "string"
        example: "String"
      listaDirecciones:
         type: "array"
         items:
          $ref: "#/definitions/listaDeDirecciones"
      rfc:
        type: "string"
        example: "String"
      listaTelefonos:
        type: "array"
        items:
          $ref: "#/definitions/listaDeTelefonos"
      listaEmails:
        type: "array"
        items:
          $ref: "#/definitions/listaDeEmail"
      tipoPersona:
        type: "string"
        example: "String"
      estatus:
        type: "string"
        example: "String"
      sucursal:
        type: "string"
        example: "String"
      vip:
        type: "string"
        example: "String"
      responseStatus:
        type: "string"
        example: "String"
      responseError:
        type: "string"
        example: "String"
      
 
          
  listaDeEmail:
    properties:
      mail:
        type: "string"
        example: "String"
      activo:
        type: boolean
        example: "Boolean"
      tipoEmail:
        type: "string"
        example: "String"
     
        
  listaDeTelefonos:
    properties:
      telefono:
        type: integer
        example: "Integer"
      tipoTelefono:
        type: "string"
        example: "String"
    
        
        
  listaDeDirecciones:
    properties:
      direccion:
        type: "string"
        example: "String"
      poblacion:
        type: "string"
        example: "String"
      ciudad:
        type: "string"
        example: "String"
      estado:
        type: "string"
        example: "String"
      cp:
        type: "string"
        example: "String"
      tipoDireccion:
        type: "string"
        example: "String"
     
 

  
