---
swagger: "2.0"
info:
  description: "Documentación de los servicios Multiva Sprint 1  <a href='http://drive.google.com/open?id=0B5MVImiMKmoPbk1RS09LWjR1aTQ'>Documento Compartido</a>" 
  version: "0.1.0"
  title: "Grupo Financiero Multiva"
host: "localhost:9090"
basePath: "/"
tags:
- name: "Core Bancario"
  description: "Primer Login (Dinámico  y Estático)"
  externalDocs:
    description: "Primer Login"
    url: "http://localhost:9090/docs"
paths:
  /consultaDatosCliente:
    post:
      tags:
      - "ESB Fuse"
      summary: "/consultaDatosCliente"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "clientePOST"
      parameters:
      - in: "body"
        name: "Cliente"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Cliente"
  /ConsultaDatosCliente:
    post:
      tags:
      - "Middleware"
      summary: "/consultaDatosCliente"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "clientePOST"
      parameters:
      - in: "body"
        name: "Cliente"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Cliente"
  /primerAcceso:
    post:
      tags:
      - "Middleware"
      summary: "/primerAcceso"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "clientePOST"
      parameters:
      - name: id
        in: "header"
        description: 'El id es el identificador  del layout que el servicio va validar'
        required: false
        type: integer

      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200_4"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Cliente"
  /MessagingCentralService:
    post:
      tags:
      - "Middleware"
      summary: "/MessagingCentralService"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "clientePOST"
      parameters:
      - in: "body"
        name: "Cliente"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Cliente"
  /consultaServiciosContratados:
    post:
      tags:
      - "ESB Fuse"
      summary: "/MessagingCentralService"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "clientePOST"
      parameters:
      - in: "body"
        name: "Cliente"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Cliente"
  /consultaProductosContratados:
    post:
      tags:
      - "ESB Fuse"
      summary: "/MessagingCentralService"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "clientePOST"
      parameters:
      - in: "body"
        name: "Cliente"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Cliente"

  /ServiciosContratados:
    post:
      tags:
      - "Middleware"
      summary: "/MessagingCentralService"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "clientePOST"
      parameters:
      - in: "body"
        name: "Cliente"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Cliente"
  /ProductosContratados:
    post:
      tags:
      - "Middleware"
      summary: "/MessagingCentralService"
      description: "Realiza la consulta de los datos del cliente"
      operationId: "clientePOST"
      parameters:
      - in: "body"
        name: "Cliente"
        description: "Estructura de la respuesta del cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        200:
          description: "estructura de la respuesta del cliente"
          schema:
            $ref: "#/definitions/inline_response_200"
        500:
          description: "el servicio tiene un error"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Cliente"

  /Validaotp:
    post:
      tags:
      - "Middleware"
      description: "Servicio que realiza la validación del OTP"
      operationId: "validaOTP"
      parameters:
      - in: "body"
        name: "validaOTP"
        description: "Se requiere la validación de VACMAN del usuario y su OTP"
        required: true
        schema:
          $ref: "#/definitions/validaOTP"
      responses:
        200:
          description: "Tipos de datos de la respuesta del servicio"
          schema:
            $ref: "#/definitions/inline_response_403_1"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "OTP"
    x-swagger-router-controller: "validaOTP"
  /Cambiapassword:
    post:
      tags:
      - "Middleware"
      description: "Se requiere la validacion de la contraseña actual despues que\
        \ se compare la nueva contraseña si los dos pasos son exitoso se requiere\
        \ realizar una modificacion al atributo userPassword en LDAP para el numero\
        \ del cleinte (uid=$numCliente,ou=people,dc=multiva,dc=mx) previamente obtenido\
        \ en la entradas y se coloca el nuevo password proporcionado."
      operationId: "cambioPwd"
      parameters:
      - in: "body"
        name: "cambioPwd"
        description: "Se requiere la validacion de la contraseña actual  "
        required: true
        schema:
          $ref: "#/definitions/cambioPwd"
      responses:
        200:
          description: "Estructura de la respuesta del servicio"
          schema:
            $ref: "#/definitions/inline_response_200_3"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        
      x-swagger-router-controller: "Contrasea"
    x-swagger-router-controller: "cambioPwd"
  /Validacontrato:
    post:
      tags:
      - "Middleware"
      description: "Este servicio es para  cambiar la bandera de que el usuario acepto el contrato"
      operationId: "contrato"
      parameters:
      - in: "body"
        name: "contrato"
        description: "Se requiere la validacion de la contraseña actual"
        required: true
        schema:
          $ref: "#/definitions/contrato"
      responses:
        200:
          description: "Tipos de datos de respuesta"
          schema:
            $ref: "#/definitions/inline_response_200_4"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Contrato"
    x-swagger-router-controller: "contrato"
 
  /validaotp:
    post:
      tags:
      - "ESB Fuse"
      description: "Servicio que realiza la validación del OTP"
      operationId: "validaOTP"
      parameters:
      - in: "body"
        name: "validaOTP"
        description: "Se requiere la validación de VACMAN del usuario y su OTP"
        required: true
        schema:
          $ref: "#/definitions/validaOTP"
      responses:
        200:
          description: "Tipos de datos de la respuesta del servicio"
          schema:
            $ref: "#/definitions/inline_response_403_1"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "OTP"
    x-swagger-router-controller: "validaOTP"
  /cambiapassword:
    post:
      tags:
      - "ESB Fuse"
      description: "Se requiere la validacion de la contraseña actual despues que\
        \ se compare la nueva contraseña si los dos pasos son exitoso se requiere\
        \ realizar una modificacion al atributo userPassword en LDAP para el numero\
        \ del cleinte (uid=$numCliente,ou=people,dc=multiva,dc=mx) previamente obtenido\
        \ en la entradas y se coloca el nuevo password proporcionado."
      operationId: "cambioPwd"
      parameters:
      - in: "body"
        name: "cambioPwd"
        description: "Se requiere la validacion de la contraseña actual  "
        required: true
        schema:
          $ref: "#/definitions/cambioPwd"
      responses:
        200:
          description: "Estructura de la respuesta del servicio"
          schema:
            $ref: "#/definitions/inline_response_200_3"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el recurso"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        
      x-swagger-router-controller: "Contrasea"
    x-swagger-router-controller: "cambioPwd"
  /validacontrato:
    post:
      tags:
      - "Seguridad Nologin"
      description: "Este servicio es para  cambiar la bandera de que el usuario acepto el contrato"
      operationId: "contrato"
      parameters:
      - in: "body"
        name: "contrato"
        description: "Se requiere la validacion de la contraseña actual"
        required: true
        schema:
          $ref: "#/definitions/contrato"
      responses:
        200:
          description: "Tipos de datos de respuesta"
          schema:
            $ref: "#/definitions/inline_response_200_4"
        500:
          description: "error en el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        404:
          description: "no se encuentra el servicio"
          schema:
            $ref: "#/definitions/inline_response_200_2"
      x-swagger-router-controller: "Contrato"
    x-swagger-router-controller: "contrato"
definitions:
  
  Cliente:
    properties:
      Numerocliente:
        type: "string"
        example: "1"
  inline_response_200:
    properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"
      DescripcionResp:
        type: "string"
        example: "string"
      NumCliente:
        type: "string"
        example: "string"
      Nombre:
        type: "string"
        example: "string"
      Direccion:
        type: "string"
        example: "string"
      Poblacion:
        type: "string"
        example: "string"
      Ciudad:
        type: "string"
        example: "string"
      Estado:
        type: "string"
        example: "string"
      CP:
        type: "string"
        example: "string"
      RFC:
        type: "string"
        example: "string"
      Telefono1:
        type: "string"
        example: "string"
      Telefono2:
        type: "string"
        example: "string"
      Celular:
        type: "string"
        example: "string"
      Mail:
        type: "string"
        example: "string"
      TipoPersona:
        type: "string"
        example: "string"
      Estatus:
        type: "string"
        example: "string"
      Sucursal:
        type: "string"
        example: "string"
      ESVIP:
        type: "string"
        example: "string"
 
  inline_response_403_1:
     properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"
      DescRespuesta:
        type: "string"
        example: "string"
      Antiphishing:
        type: "integer"
        example: "integer"
  validaOTP:
    properties:
      Usuario:
        type: "string"
        example: "123456789"
      OTP:
        type: "string"
        example: "12345tftg56577654"
      Tipo:
        type: "integer"
        example: 1
  inline_response_200_2:
    properties:
      codigoError:
        type: "integer"
        example: "integer"
      mensajeError:
        type: "string"
        example: "string"

  cambioPwd:
    properties:
      Usuario:
        type: "string"
        example: "123456789"
      Contraseña_original:
        type: "string"
        example: "12345tftg5657765412wq"
      Nueva_contraseña:
        type: "string"
        example: "12345tftg5657765412wq"
      Comprueba_contraseña:
        type: "string"
        example: "12345tftg5657765412wq"
  inline_response_200_3:
    properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"
     
 
  contrato:
    properties:
      Usuario:
        type: "string"
        example: "4333534"
      ContratoAceptado:
        type: "integer"
        example: 1
  
  inline_response_200_4:
    properties:
      CodigoRespuesta:
        type: "integer"
        example: "integer"

  
